[project]
name = "llm_graph_optimizer"
version = "0.1.0"
description = ""
authors = [
    {name = "Felix Fricke",email = "f.fricke@tum.de"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai (>=1.70.0,<2.0.0)",
    "backoff (>=2.2.1,<3.0.0)",
    "networkx (>=3.4.2,<4.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "pyvis (>=0.3.2,<0.4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "llm_graph_optimizer" },
]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"

[tool.ruff]
ignore = ["E731"]